#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import numpy as np
import SimpleITK as sitk

from functions_weighted import (
    ElastixConfig,
    apply_mask,
    apply_transform_with_transformix,
    check_same_geometry,
    create_native_reference,
    get_image_name,
    load_composite_transform,
    make_native_spacing_transform,
    make_nearest_neighbor_transform_file,
    print_image_info,
)

# ============================================================
# User settings
# ============================================================

ROOT = "/autofs/arch11/DATA/HOMES/yuchen/Minor/Organoids/Nifti_data"
DATA = os.path.join(ROOT, "case2_young", "data_final")
B_DIR = os.path.join(DATA, "data_final_bvalue")

# Microscopy image used as the fixed image during registration
FIXED_PATH = os.path.join(DATA, "case2_Topro3_high.nii")

# Eroded dMRI mask defined in the original dMRI space
MASK_PATH = os.path.join(DATA, "case2_FA_mask_LAS_eroded_2vox.nii.gz")

# Scalar dMRI-derived images transformed using the same registration
SCALAR_IMAGE_PATHS = [
    os.path.join(DATA, "dti_FA_final_LAS.nii.gz"),
    os.path.join(DATA, "dti_MD_final_LAS.nii.gz"),
    os.path.join(DATA, "dti_S0_final_LAS.nii.gz"),
]

# Individual b-value images
B_IMAGES = [os.path.join(B_DIR, f"case2_bvalue_{i:03d}.nii.gz") for i in range(1, 10)]

OUTPUT_DIR = os.path.join(DATA, "registered_testtest")
REGISTERED_DIR = os.path.join(OUTPUT_DIR, "registered")
MASKED_REGISTERED_DIR = os.path.join(OUTPUT_DIR, "registered_masked")

# Composite transform generated by the final registration pipeline
COMPOSITE_MANIFEST = os.path.join(
    ROOT,
    "registration_final_test",
    "case2_Bvalue_rigid_affine_bspline",
    "COMPOSITE_TRANSFORM",
    "composite_manifest.json",
)

TRANSFORM_CONFIG = ElastixConfig(log_to_console=False, log_to_file=False)


# ============================================================
# Main
# ============================================================

def main():
    # Check that all required inputs are available before processing
    required_paths = [FIXED_PATH, MASK_PATH, COMPOSITE_MANIFEST, *SCALAR_IMAGE_PATHS, *B_IMAGES]
    for path in required_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(path)

    for folder in [OUTPUT_DIR, REGISTERED_DIR, MASKED_REGISTERED_DIR]:
        os.makedirs(folder, exist_ok=True)

    # Load the composite transform estimated from microscopy-dMRI registration
    composite_transform = load_composite_transform(COMPOSITE_MANIFEST)

    fixed_img = sitk.ReadImage(FIXED_PATH, sitk.sitkFloat32)

    # Use an original b-value image as the reference for native dMRI voxel spacing
    native_mri_img = sitk.ReadImage(B_IMAGES[0], sitk.sitkFloat32)

    print("\n============================================================")
    print("Input geometry")
    print("============================================================")
    print_image_info("Original b-value", native_mri_img)
    print_image_info("Fixed microscopy", fixed_img)

    # Modify the composite transform output grid to use the native dMRI spacing,
    # while keeping the registered microscopy-space origin and orientation
    native_transform = os.path.join(OUTPUT_DIR, "TransformParameters_NATIVE_SPACING.txt")
    output_size, output_spacing = make_native_spacing_transform(
        composite_transform, fixed_img, native_mri_img, native_transform
    )

    # Create an explicit reference image describing the final output geometry
    native_reference = create_native_reference(fixed_img, output_size, output_spacing)

    print("\n============================================================")
    print("Output grid")
    print("============================================================")
    print(f"Size: {tuple(int(v) for v in output_size)}")
    print(f"Spacing: {tuple(float(v) for v in output_spacing)}")
    print(f"Origin: {fixed_img.GetOrigin()}")
    print(f"Direction: {fixed_img.GetDirection()}")

    print("\n============================================================")
    print("Transforming erosion mask")
    print("============================================================")

    # Use nearest-neighbor interpolation for the binary mask to avoid
    # introducing interpolated non-binary values
    mask_transform = os.path.join(OUTPUT_DIR, "TransformParameters_NATIVE_SPACING_MASK.txt")
    make_nearest_neighbor_transform_file(native_transform, mask_transform)

    mask_img = sitk.ReadImage(MASK_PATH, sitk.sitkUInt8)
    registered_mask = apply_transform_with_transformix(
        moving_sitk=mask_img,
        transform_param_path=mask_transform,
        output_dir=os.path.join(OUTPUT_DIR, "_transformix_mask"),
        config=TRANSFORM_CONFIG,
        reference_sitk=native_reference,
    )

    # Re-binarize the transformed mask and explicitly assign the output geometry
    mask_arr = sitk.GetArrayFromImage(registered_mask) > 0
    registered_mask = sitk.GetImageFromArray(mask_arr.astype(np.uint8))
    registered_mask.CopyInformation(native_reference)

    registered_mask_path = os.path.join(OUTPUT_DIR, "erosion_mask_registered_native.nii.gz")
    sitk.WriteImage(registered_mask, registered_mask_path)
    print(f"Registered mask voxels: {int(mask_arr.sum())}")

    print("\n============================================================")
    print("Transforming scalar images")
    print("============================================================")

    # Transform FA, MD, and S0 using the same registration and output grid
    for input_path in SCALAR_IMAGE_PATHS:
        name = get_image_name(input_path)

        registered_path = os.path.join(
            REGISTERED_DIR,
            f"{name}_registered_native.nii.gz",
        )
        masked_path = os.path.join(
            MASKED_REGISTERED_DIR,
            f"{name}_registered_native_masked.nii.gz",
        )

        moving_img = sitk.ReadImage(input_path, sitk.sitkFloat32)

        registered = apply_transform_with_transformix(
            moving_sitk=moving_img,
            transform_param_path=native_transform,
            output_dir=os.path.join(OUTPUT_DIR, "_transformix_tmp", name),
            config=TRANSFORM_CONFIG,
            reference_sitk=native_reference,
        )

        sitk.WriteImage(registered, registered_path)

        # Apply the transformed erosion mask after registration
        apply_mask(registered, registered_mask, masked_path)

        print(f"{name}:")
        print(f"  Registered: {registered_path}")
        print(f"  Masked:     {masked_path}")

    print("\n============================================================")
    print("Transforming b-images")
    print("============================================================")

    # Apply the same spatial transform to all individual b-value images
    for i, input_path in enumerate(B_IMAGES, start=1):
        name = f"case2_bvalue_{i:03d}"

        registered_path = os.path.join(
            REGISTERED_DIR,
            f"{name}_registered_native.nii.gz",
        )
        masked_path = os.path.join(
            MASKED_REGISTERED_DIR,
            f"{name}_registered_native_masked.nii.gz",
        )

        moving_img = sitk.ReadImage(input_path, sitk.sitkFloat32)

        registered = apply_transform_with_transformix(
            moving_sitk=moving_img,
            transform_param_path=native_transform,
            output_dir=os.path.join(OUTPUT_DIR, "_transformix_tmp", f"b{i:03d}"),
            config=TRANSFORM_CONFIG,
            reference_sitk=native_reference,
        )

        sitk.WriteImage(registered, registered_path)

        # Apply the same registered mask used for the scalar dMRI images
        apply_mask(registered, registered_mask, masked_path)

        print(f"[{i}/{len(B_IMAGES)}] {name}")
        print(f"  Registered: {registered_path}")
        print(f"  Masked:     {masked_path}")

    print("\n============================================================")
    print("Finished")
    print("============================================================")
    print(f"\nRegistered mask:\n{registered_mask_path}")
    print(f"\nRegistered images:\n{REGISTERED_DIR}")
    print(f"\nRegistered + masked images:\n{MASKED_REGISTERED_DIR}")


if __name__ == "__main__":
    main()