#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import csv
import glob
import shutil
import subprocess
import numpy as np
import SimpleITK as sitk

from functions_weighted import (
    ElastixConfig,
    apply_mask,
    apply_transform_with_transformix,
    check_same_geometry,
    create_native_reference,
    get_image_name,
    load_composite_transform,
    make_native_spacing_transform,
    make_nearest_neighbor_transform_file,
    print_image_info,
)

# ============================================================
# User settings
# ============================================================

ROOT = "/autofs/arch11/DATA/HOMES/yuchen/Minor/Organoids/Nifti_data"
DATA = os.path.join(ROOT, "case2_young", "data_final")
B_DIR = os.path.join(DATA, "data_final_bvalue")

# Microscopy image used as the fixed image during registration
FIXED_PATH = os.path.join(DATA, "case2_Topro3_high.nii")

# Eroded dMRI mask defined in the original dMRI space
MASK_PATH = os.path.join(DATA, "case2_FA_mask_LAS_eroded_2vox.nii.gz")

# Scalar dMRI-derived images transformed using the same registration
SCALAR_IMAGE_PATHS = [
    os.path.join(DATA, "dti_FA_final_LAS.nii.gz"),
    os.path.join(DATA, "dti_MD_final_LAS.nii.gz"),
    os.path.join(DATA, "dti_S0_final_LAS.nii.gz"),
]

# Individual b-value images
B_IMAGES = [os.path.join(B_DIR, f"case2_bvalue_{i:03d}.nii.gz") for i in range(1, 10)]

OUTPUT_DIR = os.path.join(DATA, "registered_testtest")
REGISTERED_DIR = os.path.join(OUTPUT_DIR, "registered")
MASKED_REGISTERED_DIR = os.path.join(OUTPUT_DIR, "registered_masked")
QC_DIR = os.path.join(OUTPUT_DIR, "QC")

TRANSFORMIX = "/homes/yuchen/software/elastix-5.3.1/bin/transformix"

# Composite transform generated by the final registration pipeline
COMPOSITE_MANIFEST = os.path.join(
    ROOT,
    "registration_final_test",
    "case2_Bvalue_rigid_affine_bspline",
    "COMPOSITE_TRANSFORM",
    "composite_manifest.json",
)

TRANSFORM_CONFIG = ElastixConfig(log_to_console=False, log_to_file=False)


# ============================================================
# Jacobian helpers
# ============================================================

def find_jacobian_image(folder):
    patterns = [
        "*spatialJacobian*.nii",
        "*spatialJacobian*.nii.gz",
        "*spatialJacobian*.mhd",
        "*jacobian*.nii",
        "*jacobian*.nii.gz",
        "*jacobian*.mhd",
    ]
    found = []
    for pattern in patterns:
        found.extend(glob.glob(os.path.join(folder, pattern)))
    found = sorted(set(found))
    if not found:
        raise RuntimeError(f"Jacobian image not found: {folder}")
    return found[0]


def compute_jacobian(transform_path, output_path, temp_dir):
    if os.path.isdir(temp_dir):
        shutil.rmtree(temp_dir)
    os.makedirs(temp_dir, exist_ok=True)
    subprocess.run([TRANSFORMIX, "-jac", "all", "-out", temp_dir, "-tp", transform_path], check=True)
    result_path = find_jacobian_image(temp_dir)
    jacobian = sitk.ReadImage(result_path, sitk.sitkFloat32)
    sitk.WriteImage(jacobian, output_path)
    return jacobian


def orient_jacobian(jacobian, mask, output_path):
    if not check_same_geometry(jacobian, mask):
        raise RuntimeError("Jacobian and mask geometry mismatch.")
    jac = sitk.GetArrayFromImage(jacobian).astype(np.float32)
    mask_data = sitk.GetArrayFromImage(mask) > 0
    values = jac[mask_data & np.isfinite(jac)]
    if values.size == 0:
        raise RuntimeError("No valid Jacobian voxels inside mask.")
    raw_median = float(np.median(values))
    if abs(raw_median) < 1e-12:
        raise RuntimeError("Jacobian median inside mask is approximately zero; cannot determine global orientation.")
    global_sign = 1.0 if raw_median > 0 else -1.0
    oriented = sitk.GetImageFromArray((jac * global_sign).astype(np.float32))
    oriented.CopyInformation(jacobian)
    sitk.WriteImage(oriented, output_path)
    return oriented, int(global_sign), raw_median


def save_jacobian_statistics(jacobian, mask, output_path, global_sign_applied, raw_median):
    if not check_same_geometry(jacobian, mask):
        raise RuntimeError("Jacobian and mask geometry mismatch.")
    jac = sitk.GetArrayFromImage(jacobian).astype(np.float64)
    mask_data = sitk.GetArrayFromImage(mask) > 0
    values = jac[mask_data & np.isfinite(jac)]
    if values.size == 0:
        raise RuntimeError("No valid Jacobian voxels inside mask.")
    stats = {
        "mean": float(np.mean(values)),
        "std": float(np.std(values)),
        "min": float(np.min(values)),
        "p01": float(np.percentile(values, 1)),
        "median": float(np.median(values)),
        "p99": float(np.percentile(values, 99)),
        "max": float(np.max(values)),
        "raw_median_before_orientation": float(raw_median),
        "global_sign_applied": int(global_sign_applied),
        "n_voxels": int(values.size),
        "n_folding": int(np.sum(values <= 0)),
    }
    with open(output_path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(stats.keys())
        writer.writerow(stats.values())
    return stats


# ============================================================
# Main
# ============================================================

def main():
    # Check that all required inputs are available before processing
    required_paths = [TRANSFORMIX, FIXED_PATH, MASK_PATH, COMPOSITE_MANIFEST, *SCALAR_IMAGE_PATHS, *B_IMAGES]
    for path in required_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(path)

    for folder in [OUTPUT_DIR, REGISTERED_DIR, MASKED_REGISTERED_DIR, QC_DIR]:
        os.makedirs(folder, exist_ok=True)

    # Load the composite transform estimated from microscopy-dMRI registration
    composite_transform = load_composite_transform(COMPOSITE_MANIFEST)

    fixed_img = sitk.ReadImage(FIXED_PATH, sitk.sitkFloat32)

    # Use an original b-value image as the reference for native dMRI voxel spacing
    native_mri_img = sitk.ReadImage(B_IMAGES[0], sitk.sitkFloat32)

    print("\n============================================================")
    print("Input geometry")
    print("============================================================")
    print_image_info("Original b-value", native_mri_img)
    print_image_info("Fixed microscopy", fixed_img)

    # Modify the composite transform output grid to use the native dMRI spacing,
    # while keeping the registered microscopy-space origin and orientation
    native_transform = os.path.join(OUTPUT_DIR, "TransformParameters_NATIVE_SPACING.txt")
    output_size, output_spacing = make_native_spacing_transform(
        composite_transform, fixed_img, native_mri_img, native_transform
    )

    # Create an explicit reference image describing the final output geometry
    native_reference = create_native_reference(fixed_img, output_size, output_spacing)

    print("\n============================================================")
    print("Output grid")
    print("============================================================")
    print(f"Size: {tuple(int(v) for v in output_size)}")
    print(f"Spacing: {tuple(float(v) for v in output_spacing)}")
    print(f"Origin: {fixed_img.GetOrigin()}")
    print(f"Direction: {fixed_img.GetDirection()}")

    print("\n============================================================")
    print("Transforming erosion mask")
    print("============================================================")

    # Use nearest-neighbor interpolation for the binary mask to avoid
    # introducing interpolated non-binary values
    mask_transform = os.path.join(OUTPUT_DIR, "TransformParameters_NATIVE_SPACING_MASK.txt")
    make_nearest_neighbor_transform_file(native_transform, mask_transform)

    mask_img = sitk.ReadImage(MASK_PATH, sitk.sitkUInt8)
    registered_mask = apply_transform_with_transformix(
        moving_sitk=mask_img,
        transform_param_path=mask_transform,
        output_dir=os.path.join(OUTPUT_DIR, "_transformix_mask"),
        config=TRANSFORM_CONFIG,
        reference_sitk=native_reference,
    )

    # Re-binarize the transformed mask and explicitly assign the output geometry
    mask_arr = sitk.GetArrayFromImage(registered_mask) > 0
    registered_mask = sitk.GetImageFromArray(mask_arr.astype(np.uint8))
    registered_mask.CopyInformation(native_reference)

    registered_mask_path = os.path.join(OUTPUT_DIR, "erosion_mask_registered_native.nii.gz")
    sitk.WriteImage(registered_mask, registered_mask_path)
    print(f"Registered mask voxels: {int(mask_arr.sum())}")

    print("\n============================================================")
    print("Computing Jacobian determinant")
    print("============================================================")

    # Compute the raw Jacobian determinant map from the final transform
    raw_jacobian_path = os.path.join(QC_DIR, "jacobian_determinant_raw_native.nii.gz")
    raw_jacobian = compute_jacobian(
        native_transform,
        raw_jacobian_path,
        os.path.join(QC_DIR, "_transformix_jacobian"),
    )

    # Correct a possible global sign inversion using the median inside the registered mask
    jacobian_path = os.path.join(QC_DIR, "jacobian_determinant_native.nii.gz")
    jacobian, global_sign, raw_median = orient_jacobian(
        raw_jacobian, registered_mask, jacobian_path
    )

    # Save a masked Jacobian map for visual QC and quantitative inspection
    jacobian_masked_path = os.path.join(QC_DIR, "jacobian_determinant_native_masked.nii.gz")
    apply_mask(jacobian, registered_mask, jacobian_masked_path)

    jacobian_stats_path = os.path.join(QC_DIR, "jacobian_statistics_masked.csv")
    jac_stats = save_jacobian_statistics(
        jacobian, registered_mask, jacobian_stats_path, global_sign, raw_median
    )

    print(f"Raw Jacobian median:  {raw_median:.6f}")
    print(f"Global sign applied:  {global_sign:+d}")
    print(f"Jacobian mean:        {jac_stats['mean']:.6f}")
    print(f"Jacobian median:      {jac_stats['median']:.6f}")
    print(f"Jacobian min:         {jac_stats['min']:.6f}")
    print(f"Jacobian max:         {jac_stats['max']:.6f}")
    print(f"Jacobian folding:     {jac_stats['n_folding']}")

    if jac_stats["n_folding"] > 0:
        raise RuntimeError(f"Detected {jac_stats['n_folding']} folding voxels inside mask.")

    print("\n============================================================")
    print("Transforming scalar images")
    print("============================================================")

    # Transform FA, MD, and S0 using the same registration and output grid
    for input_path in SCALAR_IMAGE_PATHS:
        name = get_image_name(input_path)

        registered_path = os.path.join(
            REGISTERED_DIR,
            f"{name}_registered_native.nii.gz",
        )
        masked_path = os.path.join(
            MASKED_REGISTERED_DIR,
            f"{name}_registered_native_masked.nii.gz",
        )

        moving_img = sitk.ReadImage(input_path, sitk.sitkFloat32)

        registered = apply_transform_with_transformix(
            moving_sitk=moving_img,
            transform_param_path=native_transform,
            output_dir=os.path.join(OUTPUT_DIR, "_transformix_tmp", name),
            config=TRANSFORM_CONFIG,
            reference_sitk=native_reference,
        )

        sitk.WriteImage(registered, registered_path)

        # Apply the transformed erosion mask after registration
        apply_mask(registered, registered_mask, masked_path)

        print(f"{name}:")
        print(f"  Registered: {registered_path}")
        print(f"  Masked:     {masked_path}")

    print("\n============================================================")
    print("Transforming b-images")
    print("============================================================")

    # Apply the same spatial transform to all individual b-value images
    for i, input_path in enumerate(B_IMAGES, start=1):
        name = f"case2_bvalue_{i:03d}"

        registered_path = os.path.join(
            REGISTERED_DIR,
            f"{name}_registered_native.nii.gz",
        )
        masked_path = os.path.join(
            MASKED_REGISTERED_DIR,
            f"{name}_registered_native_masked.nii.gz",
        )

        moving_img = sitk.ReadImage(input_path, sitk.sitkFloat32)

        registered = apply_transform_with_transformix(
            moving_sitk=moving_img,
            transform_param_path=native_transform,
            output_dir=os.path.join(OUTPUT_DIR, "_transformix_tmp", f"b{i:03d}"),
            config=TRANSFORM_CONFIG,
            reference_sitk=native_reference,
        )

        sitk.WriteImage(registered, registered_path)

        # Apply the same registered mask used for the scalar dMRI images
        apply_mask(registered, registered_mask, masked_path)

        print(f"[{i}/{len(B_IMAGES)}] {name}")
        print(f"  Registered: {registered_path}")
        print(f"  Masked:     {masked_path}")

    print("\n============================================================")
    print("Finished")
    print("============================================================")
    print(f"\nRegistered mask:\n{registered_mask_path}")
    print(f"\nRegistered images:\n{REGISTERED_DIR}")
    print(f"\nRegistered + masked images:\n{MASKED_REGISTERED_DIR}")
    print(f"\nJacobian determinant:\n{jacobian_path}")
    print(f"\nMasked Jacobian determinant:\n{jacobian_masked_path}")
    print(f"\nJacobian statistics:\n{jacobian_stats_path}")


if __name__ == "__main__":
    main()