#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import numpy as np
import SimpleITK as sitk

from functions_weighted import (
    ElastixConfig,
    MetricConfig,
    apply_transform_with_transformix,
    compute_metrics,
    create_native_reference,
    load_transform_from_registration_dir,
    make_native_spacing_transform,
    print_image_info,
    resample_mask_to_native,
    resample_microscopy_to_native,
    save_run_metrics,
    upsert_registration_summary_table,
)

# ============================================================
# User settings
# ============================================================

ROOT = "/autofs/arch11/DATA/HOMES/yuchen/Minor/Organoids/Nifti_data"
DATA = os.path.join(ROOT, "case2_young", "data_final")
B_DIR = os.path.join(DATA, "data_final_bvalue")

# Fixed microscopy image used during registration
FIXED_PATH = os.path.join(DATA, "case2_Topro3_high.nii")

# Evaluation mask used for mask-restricted registration metrics
MASK_PATH = os.path.join(DATA, "case2_FA_mask_LAS_dilated_10vox_registered_native.nii.gz")

# dMRI-derived images used to evaluate the same registration transform
BVALUE9_PATH = os.path.join(B_DIR, "case2_bvalue_009.nii.gz")
MD_PATH = os.path.join(DATA, "case2_MD_LAS.nii.gz")
FA_PATH = os.path.join(DATA, "case2_FA_LAS.nii.gz")
S0_PATH = os.path.join(DATA, "case2_S0_LAS.nii.gz")

# Registration result to be evaluated
REGISTRATION_DIR = os.path.join(ROOT, "registration_native_pipeline", "case2_FA_rigid_affine")
INPUT_IMAGE_LABEL = "FA"
REGISTRATION_LABEL = "Rigid_Affine"

# All images are transformed with the same registration before metric calculation
EVAL_IMAGES = {
    "BVALUE9": BVALUE9_PATH,
    "MD": MD_PATH,
    "FA": FA_PATH,
    "S0": S0_PATH,
}

# Generate a consistent name for this registration evaluation run
RUN_NAME = (
    INPUT_IMAGE_LABEL.replace(":", "_").replace(",", "_").replace(" ", "_")
    + "_"
    + REGISTRATION_LABEL.replace("+", "_").replace(" ", "_")
)

OUTPUT_DIR = os.path.join(DATA, "registration_metric_evaluation_erosion1voxelmask", RUN_NAME)
REGISTERED_DIR = os.path.join(OUTPUT_DIR, "registered")
QC_DIR = os.path.join(OUTPUT_DIR, "QC")
TABLE_CSV = os.path.join(DATA, "registration_metric_table.csv")

# MI and NCC are calculated globally and inside the evaluation mask
METRIC_CONFIG = MetricConfig(hist_bins=64, score_method="MI_global")
TRANSFORM_CONFIG = ElastixConfig(log_to_console=False, log_to_file=False)


# ============================================================
# Main
# ============================================================

def main():
    # Check that all required registration and image inputs are available
    required_paths = [REGISTRATION_DIR, FIXED_PATH, MASK_PATH, *EVAL_IMAGES.values()]
    for path in required_paths:
        if not os.path.exists(path):
            raise FileNotFoundError(path)

    # Load the final transform generated by the selected registration run
    manifest_path, transform_path = load_transform_from_registration_dir(REGISTRATION_DIR)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(REGISTERED_DIR, exist_ok=True)
    os.makedirs(QC_DIR, exist_ok=True)

    fixed_img = sitk.ReadImage(FIXED_PATH, sitk.sitkFloat32)
    mask_img = sitk.ReadImage(MASK_PATH, sitk.sitkUInt8)

    # B-value 9 is used as the reference for the native dMRI voxel spacing
    native_mri_img = sitk.ReadImage(BVALUE9_PATH, sitk.sitkFloat32)

    print("\n============================================================")
    print(f"Run: {INPUT_IMAGE_LABEL} | {REGISTRATION_LABEL}")
    print("============================================================")
    print(f"Registration dir: {REGISTRATION_DIR}")
    print(f"Manifest: {manifest_path}")
    print(f"Transform: {transform_path}")
    print(f"Evaluation mask: {MASK_PATH}")
    print_image_info("Native MRI reference", native_mri_img)
    print_image_info("Fixed microscopy", fixed_img)
    print_image_info("Fixed evaluation mask", mask_img)

    # Adapt the registration output grid to the native dMRI spacing while
    # preserving the registered microscopy-space origin and orientation
    native_transform = os.path.join(OUTPUT_DIR, "TransformParameters_NATIVE_SPACING.txt")
    output_size, output_spacing = make_native_spacing_transform(
        transform_path, fixed_img, native_mri_img, native_transform
    )
    native_reference = create_native_reference(fixed_img, output_size, output_spacing)

    # Resample the fixed microscopy image onto the same native-resolution grid
    # used for all transformed dMRI images
    microscopy_native_path = os.path.join(QC_DIR, "microscopy_native_spacing.nii.gz")
    microscopy_native = resample_microscopy_to_native(
        fixed_img, native_reference, microscopy_native_path
    )

    # Resample the evaluation mask onto exactly the same grid used for metric calculation
    mask_native_path = os.path.join(QC_DIR, "evaluation_mask_native_spacing.nii.gz")
    mask_native = resample_mask_to_native(mask_img, native_reference, mask_native_path)
    print(f"Evaluation mask voxels: {int(np.sum(sitk.GetArrayFromImage(mask_native) > 0))}")

    output_names = {
        "BVALUE9": "bvalue_009_registered_native.nii.gz",
        "MD": "MD_registered_native.nii.gz",
        "FA": "FA_registered_native.nii.gz",
        "S0": "S0_registered_native.nii.gz",
    }

    metrics = {}

    print("\n============================================================")
    print("Transforming B9 / MD / FA / S0 and calculating MI + NCC")
    print("============================================================")

    # Apply the same registration transform to all evaluation images and
    # calculate global and mask-restricted MI/NCC against the microscopy image
    for name in ["BVALUE9", "MD", "FA", "S0"]:
        registered_path = os.path.join(REGISTERED_DIR, output_names[name])

        moving_img = sitk.ReadImage(EVAL_IMAGES[name], sitk.sitkFloat32)

        registered = apply_transform_with_transformix(
            moving_sitk=moving_img,
            transform_param_path=native_transform,
            output_dir=os.path.join(OUTPUT_DIR, "_transformix_tmp", name),
            config=TRANSFORM_CONFIG,
            reference_sitk=native_reference,
        )

        sitk.WriteImage(registered, registered_path)

        # Calculate metrics over the full valid image region and inside the mask
        result = compute_metrics(
            microscopy_native,
            registered,
            config=METRIC_CONFIG,
            mask_img=mask_native,
        )

        result["registered_path"] = registered_path
        metrics[name] = result

        print(
            f"{name:8s} | "
            f"Global MI={result['MI_global']:.6f}, NCC={result['NCC_global']:.6f}, "
            f"n={result['valid_voxels_global']} | "
            f"Mask MI={result['MI_mask']:.6f}, NCC={result['NCC_mask']:.6f}, "
            f"n={result['valid_voxels_mask']}"
        )

    # Save detailed metrics for this run
    run_metrics_path = os.path.join(QC_DIR, "metrics_B9_MD_FA_S0.csv")
    save_run_metrics(
        metrics,
        run_metrics_path,
        image_order=["BVALUE9", "MD", "FA", "S0"],
    )

    # Add or update this registration result in the overall comparison table
    upsert_registration_summary_table(
        metrics,
        TABLE_CSV,
        INPUT_IMAGE_LABEL,
        REGISTRATION_LABEL,
    )

    print("\n============================================================")
    print("Result")
    print("============================================================")

    for name in ["BVALUE9", "MD", "FA", "S0"]:
        result = metrics[name]
        print(
            f"{name:8s} | Global MI={result['MI_global']:.6f}, NCC={result['NCC_global']:.6f} | "
            f"Mask MI={result['MI_mask']:.6f}, NCC={result['NCC_mask']:.6f}"
        )

    print(f"\nRegistered images:\n{REGISTERED_DIR}")
    print(f"\nEvaluation mask:\n{mask_native_path}")
    print(f"\nThis-run metrics:\n{run_metrics_path}")
    print(f"\nSummary table:\n{TABLE_CSV}")


if __name__ == "__main__":
    main()